### ISSUE TITLE
How can i install Espressif MCU and .zip file libraries in Pro IDE?

### ISSUE THREAD

**Issue by tanphat110699** [arduino/arduino-pro-ide#231] opened 2020-03-20 08:42 UTC
This Pro IDE make me impressed a lot. But...
How can i install Espressif MCU and .zip file libraries in Pro IDE?
Pls help

**Comment by per1234** [comment] 2020-03-20 08:47
>How can i install Espressif MCU

Duplicate of https://github.com/arduino/arduino-pro-ide/issues/103

>and .zip file libraries

Duplicate of https://github.com/arduino/arduino-pro-ide/issues/128

>Pls help

This is a place to report bugs and make feature requests. If you are just looking for help, the place to do that is on the [Arduino Forum](http://forum.arduino.cc/index.php?topic=148850). We can definitely help you out over there.

**Closed by per1234** 2020-03-20 08:47 UTC
Labels: enhancement
