### ISSUE TITLE
avrdude: stk500_recv(): programmer is not responding avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x00

### ISSUE THREAD

**Issue by StipeElektrotechnik** [arduino/arduino-pro-ide#221] opened 2020-02-29 15:06 UTC
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x00

I gonna use the Arduino Nano with the old boot loader how I switch in the new Arduino Pro IDE the bootoader

**Comment by per1234** [comment] 2020-03-14 12:44
Closing as duplicate of https://github.com/arduino/arduino-pro-ide/issues/10

**Closed by per1234** 2020-03-14 12:44 UTC
Labels: bug
