### ISSUE TITLE
Windows protected your PC

### ISSUE THREAD

**Issue by chovanj** [arduino/arduino-pro-ide#100] opened 2019-10-25 17:05 UTC
If I want to start Arduino Pro IDE clicking on the exe file it displays that dialog in the screenshot. The workaround is to open command-line and type Arduino Pro IDE.exe then it works without the dialog.

1. Click on 'Arduino Pro IDE.exe'

![image](https://user-images.githubusercontent.com/22910341/67589868-d2112600-f759-11e9-92f1-aa86b77c6597.png)

 - OS: Windows 10
 - Version 1903
- Arduino Pro IDE: arduino-pro-ide-0.0.2-alpha.preview-windows

**Comment by mastrolinux** [comment] 2019-10-25 22:29
You can also click more info and then run anyway. This is not a bug because is an alpha version not intended to be signed. Closing this for now, we know it has to be signed when moved out of the Alpha

**Closed by mastrolinux** 2019-10-25 22:29 UTC
Labels: bug
