### ISSUE TITLE
Missing Processor selection option 

### ISSUE THREAD

**Issue by rnbokade** [arduino/arduino-pro-ide#104] opened 2019-10-26 08:28 UTC
The processor selection option e.g. the one that used to come when Arduino pro mini used to be selected is missing in this. Please add it to the release soon. I don't think it would be that hard

**Comment by Erriez** [comment] 2019-10-28 19:10
Yes, the `board` and `processor` menu's are missing in in new IDE v0.0.2 Alpha:
![image](https://user-images.githubusercontent.com/8849873/67709591-890ddb80-f9be-11e9-8007-38883a920d25.png)


Original Arduino IDE:
![image](https://user-images.githubusercontent.com/8849873/67709539-6bd90d00-f9be-11e9-9289-d42eb937c0b2.png)

Now I can't use my favorite `Pro or Pro Mini 3V3 8MHz board` and my custom boards with the new IDE.

**Comment by HiFiJ** [comment] 2020-04-01 19:15
Hi everyone,

I am also missing this option; out of luck for now with my Pro Mini 3.3V boards. 
Thanks for the work on the new IDE in general, would love to use it!

**Comment by Master811129** [comment] 2020-04-01 19:39
> Yes, the `board` and `processor` menu's are missing in in new IDE v0.0.2 Alpha:
> ![image](https://user-images.githubusercontent.com/8849873/67709591-890ddb80-f9be-11e9-8007-38883a920d25.png)
> 
> Original Arduino IDE:
> ![image](https://user-images.githubusercontent.com/8849873/67709539-6bd90d00-f9be-11e9-9289-d42eb937c0b2.png)
> 
> Now I can't use my favorite `Pro or Pro Mini 3V3 8MHz board` and my custom boards with the new IDE.

I think this is #10. It'll be available in the next release

**Comment by per1234** [comment] 2020-04-02 00:17
Closing as duplicate of #10

Thanks @Master811129!

**Closed by per1234** 2020-04-02 00:17 UTC
Labels: enhancement
