### ISSUE TITLE
Serial monitor struggles to communicate

### ISSUE THREAD

**Issue by RunarSJ** [arduino/arduino-pro-ide#132] opened 2019-11-06 19:57 UTC
I uploaded a serial passthrough code to a an arduino uno using the softwareserial library to communicate with a hm10 bluetooth module. Configuring did not work at all in PRO IDE environment, but worked instantly in the normal IDE environment.

**Comment by kittaakos** [comment] 2019-11-26 13:06
> uploaded a serial passthrough code to a an arduino uno using the softwareserial library to communicate with a hm10 bluetooth module

> but worked instantly in the normal IDE environment

@RunarSJ, can you please me give some hints (screenshot, screencast, or whatever is the easiest for you) on reproducing this? What exactly did you do in the Java IDE and the PRO IDE? What board did you use, what cores were installed, and so on? Thank you!

**Comment by mastrolinux** [comment] 2020-01-08 15:39
Closing due to lack of info.

**Closed by mastrolinux** 2020-01-08 15:39 UTC
Labels: :thinking: needs more info, bug, 🔎 serial-monitor
