### ISSUE TITLE
Custom boards do not work on 0.0.5 version

### ISSUE THREAD

**Issue by caiossoliveira** [arduino/arduino-pro-ide#233] opened 2020-03-22 20:31 UTC
Custom boards do not work on 0.0.5 version.

Despite issue #103, the steps only work on the previous versions.

 - Ubuntu 18.04
 - Arduino IDE Pro Version 0.0.5

**Comment by per1234** [comment] 2020-03-22 20:44
Closing as duplicate of https://github.com/arduino/arduino-pro-ide/issues/215

**Closed by per1234** 2020-03-22 20:44 UTC
Labels: bug
