### ISSUE TITLE
Can't open parentheses

### ISSUE THREAD

**Issue by Luiza1201** [arduino/arduino-pro-ide#148] opened 2019-11-23 23:12 UTC
**Describe the bug**
I can't open parentheses. Every time I click Shift + 9 it acts like I've pressed Shift+Home.

**To Reproduce**
1.Press Shift+9

**Expected behavior**
I expected it to open parentheses normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/58123303/69486636-84590d80-0e2c-11ea-9c74-e0c2d08768de.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1903

**Additional context**
I also tested in the normal Arduino ide, word and chrome to see if it wasn't a problem on my computer or keyboard and in all of those softwares the parentheses opened normally without a problem

**Comment by svenefftinge** [comment] 2019-11-28 07:22
This is a duplicate of #129. Adding that one to the new milestone instead.

**Closed by svenefftinge** 2019-11-28 07:22 UTC
Labels: bug
