### ISSUE TITLE
Build/Output folders

### ISSUE THREAD

**Issue by ag88** [arduino/arduino-pro-ide#170] opened 2020-01-04 16:36 UTC
the arduino pro ide is a big improvement as it provides the much needed reference jumps (e.g. drill in to functions, reference jumps to definitions and structures)

**Is your feature request related to a problem? Please describe.**
one of my frustrations with Arduino IDE is the use of temporary folders for build.
this is really a bad idea as sketches are 'growing up' some are full blown apps such as 3d printing firmware. what is really really needed is a means for users to specify the output folder, this can be a default output folder such as Build in the sketch folder

the compiled binary should be left in the build folder so that the user can move it to an archive if they so desire.  the separation of the build from the install step is a rudimentary 'must have'. the reason is that Arduino boards (and all the mcu dev boards) these days are 'single firmware' apps. swap that firmware and it takes on a different role,
hence there would be many different 'firmware' binaries and users should be able to install the firmware themselves through a separate app/utility of their choosing. e.g. a command line install utility

**Describe the solution you'd like**
there should be a build/output folder in the sketch folder rather than temporary builds and compiles should place build outputs and binary in the build/output folder. (not temporary)
user should be able to change that default build/output folder in config/settings
sketches are getting (very) large, using static output folders is very much a 'must have'.
build binary should be placed in the output folder so that users can manually install the binary from the command line if they so choose. 

if possible please implement incremental build, that task probably belongs to the arduino-cli

**Describe alternatives you've considered**
i've not used the Arduino IDE but rather switched to Eclipse and makefile biulds simply because the build outputs are placed in the output folder (with incremental builds).  In addition is the missing 'feature' of code/symbol reference jumps that i depended on in eclipse

**Comment by spoenemann** [comment] 2020-01-13 14:56
Duplicate of #130

**Closed by spoenemann** 2020-01-13 14:56 UTC
Labels: enhancement
