### ISSUE TITLE
Can not upload to cheap Arduino Nano

### ISSUE THREAD

**Issue by simoonvance** [arduino/arduino-pro-ide#222] opened 2020-02-29 18:55 UTC
The arduino nano I'm using has the ATmega 328P (old bootloader), but I can not upload to it.

**Comment by Master811129** [comment] 2020-02-29 20:31
#10

**Comment by per1234** [comment] 2020-02-29 20:36
Closing as duplicate of https://github.com/arduino/arduino-pro-ide/issues/10

**Closed by per1234** 2020-02-29 20:36 UTC
Labels: enhancement
