### ISSUE TITLE
--->WHAT HAPPEN WITH YOU?

### ISSUE THREAD

**Issue by agratx** [arduino/arduino-pro-ide#159] opened 2019-11-30 04:35 UTC
I don't like it, because I can't use it as an ISP programmer--->WHAT HAPPEN WITH YOU?

In normal mode, it should be functional as the normal IDE, and in advanced mode as it should behave as such. I don't think you have made the great revolution that you are announcing if the transition is from earth to heaven if you have excluded all of the above in this new Arduino Pro IDE

--->WHAT HAPPEN WITH YOU?

**Comment by per1234** [comment] 2019-11-30 04:52
Closing as duplicate of https://github.com/arduino/arduino-pro-ide/issues/158

@agratx it's not helpful to create duplicate issues.

Also, please use descriptive issue titles in the future. An issue titled "--->WHAT HAPPEN WITH YOU?" requires everyone to open and read the issue just to find out what it's about. That wastes time that could be spent improving the software instead.

**Closed by per1234** 2019-11-30 04:52 UTC
Labels: bug
