### ISSUE TITLE
Error: No core is installed for Arduino Uno.

### ISSUE THREAD

**Issue by chovanj** [arduino/arduino-pro-ide#91] opened 2019-10-23 08:30 UTC
**Describe the bug**
After installing Arduino AVR Boards and selecting Arduino UNO from the list, it's still shouting **"Error: No core is installed for Arduino Uno. Please install the board"**.

1. Open a new sketch for the first time.
2. Install Arduino AVR Boards.
3. Select Arduino UNO.
4. Click on Verify.

![image](https://user-images.githubusercontent.com/22910341/67373281-a76b7580-f57f-11e9-9c2a-f4675ec1ad13.png)

![image](https://user-images.githubusercontent.com/22910341/67373445-ec8fa780-f57f-11e9-83c6-491e05dd8e9f.png)

 - OS: Windows 10 Pro
 - Version: 1903
- Arduino Pro IDE: v0.0.1-alpha.preview-snapshot-20191021.1

**Comment by mastrolinux** [comment] 2019-10-23 09:07
We are not able to reproduce, are you able to provide the full output of the developer tool? 
Ctrl + Alt + I in the app to open the Developer Tools.

**Comment by chovanj** [comment] 2019-10-23 09:12
It's a very strange because even I can't do :-). 

When I try again to select the board "Arduino Uno" disappeared and only "Arduino/Genuino UNO" stays which works after selecting. No idea how "Arduino UNO" appeared in the list for the first time and why it disappeared.

**Comment by Fede85** [comment] 2019-10-23 09:16
Same issue here despite it's a MKRZero:
![Screenshot from 2019-10-21 17-25-21](https://user-images.githubusercontent.com/731214/67377275-b48b6300-f585-11e9-940a-263ffff6782a.png)

**Comment by mastrolinux** [comment] 2019-10-23 09:31
@Fede85 is it just the pop up or the sketch does not compile?

**Comment by Fede85** [comment] 2019-10-23 10:03
The pop-up appear when I click the verify button. And the sketch doesn't compile.
The SAMD core was installed from the ide 1.8.x some time ago (it isn't the latest version). But should be ok for the MKRZero.
Maybe if you want to try to replicate there, you can install the same version of SAMD core  through the Board Manager of the "normal" IDE and then try to open the PRO IDE.

BTW, I'm using Ubuntu 19.10

**Comment by RobDeVoer** [comment] 2019-10-24 21:56
I also had the Arduino Uno popup appear. It disappeared after installing Arduino AVR Boards. Could not compile until after I closed ide and restarted.

(Using Windows 10)

**Comment by mastrolinux** [comment] 2019-10-25 16:43
Please try https://github.com/arduino/arduino-pro-ide/releases/tag/v0.0.2-alpha.preview and let us know

**Comment by Fede85** [comment] 2019-10-29 11:18
![image](https://user-images.githubusercontent.com/731214/67762395-9fab4580-fa45-11e9-8a7c-b576bd7b49ee.png)

Still the same.

It may help: I had the same behavior with the **Arduino nrf528x** core. After updating to the latest with the classic Arduino IDE I was able to compile with the pro-IDE

**Comment by greggwardnz** [comment] 2019-10-30 03:55
Same for Nano. This is on Ubuntu 19.10 using v0.0.2 of Pro IDE:

![image](https://user-images.githubusercontent.com/2172727/67827754-d1033e80-fb35-11e9-83c8-a37758f8f3ad.png)

**Comment by ubidefeo** [comment] 2020-08-26 06:35
@abionics 
yesterday we released new CLI and new Pro IDE
can you test `0.1.0` and let me know if it gets better for you?

thank you

**Comment by per1234** [comment] 2021-02-18 23:18
Hi all. Thanks so much for your valuable feedback,

Would you mind downloading [the new 0.1.4 release of Arduino Pro IDE](https://github.com/arduino/arduino-pro-ide/releases/tag/0.1.4) and letting us know whether the bug still occurs?

There have been some nice advancements since the time of your reports, so I think the issue might have been fixed along the way.

**Comment by ubidefeo** [comment] 2021-02-19 15:56
@per1234 as you can see on Aug 26 2020 I already asked @abionics to test v 0.1.0 and we never got a reply.
I will therefore close this issue.
Please, @abionics , let us know and reopen in case

**Closed by ubidefeo** 2021-02-19 15:56 UTC
Labels: bug, waiting for feedback

**Comment by ubidefeo** [comment] 2021-02-19 18:28
thank you for reacting so quick, @abionics 🙏🏼
