### ISSUE TITLE
Board Selection sporadically switching between different boards

### ISSUE THREAD

**Issue by nikilase** [arduino/arduino-pro-ide#38] opened 2019-10-20 11:23 UTC
As you can see in this GIF the Board selection sporadically switches between three different boards.  

**To Reproduce**
Only tested with Uno WiFi Rev2
1. Start Arduino Pro IDE
2. If not done already, install the board package for the Uno WiFi Rev2
3. connect Uno WiFi Rev2 to Computer
4. select the Board and Port in the Board Selection
5. expand the board dropdown menu

**Expected behavior**
The dropdown should not have a red x but a green check mark. 
Also in the dropdown it should not change between different boards, but stay at the Uno WiFi Rev2.

**Screenshots**
![ArduinoArduinoEditor2019-10-2012](https://user-images.githubusercontent.com/38077998/67158778-90891100-f33c-11e9-8d0f-eb01e12a131b.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Version Build 18362

**Comment by kittaakos** [comment] 2020-04-09 07:42
I could not reproduce the issue with the current state. We have completely rewritten the logic: https://github.com/arduino/arduino-pro-ide/issues/198#issuecomment-600059664

I am going to close this. Please reopen if the defect still persists.

**Closed by kittaakos** 2020-04-09 07:42 UTC
Labels: bug
