### ISSUE TITLE
tabs do not have the closing "x"

### ISSUE THREAD

**Issue by DaRaymond1** [arduino/arduino-pro-ide#29] opened 2019-10-20 07:28 UTC
Tabs inside the IDE do not have the closing "x" and when right clicking and selecting close nothing happens. as far as i can tell there are no ways of closing tabs other than closing the entire IDE.

**Comment by Fede85** [comment] 2019-10-20 19:05
The "Advanced mode" allows you to close the files. The issue seems related only to the "Classic mode"

**Comment by MrRSquared** [comment] 2019-10-20 21:27
Even if you right click on the tab and select close (or any variation, close to the right etc. ), nothing closes.  Maximize and minimize work.  In the dark version of pro mode, it is difficult to see the xs, but they are there and work as expected.

**Comment by mastrolinux** [comment] 2019-10-28 13:30
This is the intended behavior. It is the same in the Arduino classic IDE. Closing the issue.

**Closed by mastrolinux** 2019-10-28 13:30 UTC
Labels: bug
