### ISSUE TITLE
Theme is not consistent between views

### ISSUE THREAD

**Issue by MrRSquared** [arduino/arduino-pro-ide#53] opened 2019-10-20 21:40 UTC
**Describe the bug**
Theme is not persistent between views (classic v pro).

**To Reproduce**
1. In the current mode, select 'File -> Settings ->Change Color Theme'
2. Click on 'Any of the three theme options'
3. After the window refreshes with the selected theme,
4. Click 'Toggle Advanced Mode'

**Expected behavior**
Either the interface would keep the selected theme, or revert back to the one chosen in the interface version before.
E.X.
If you chose Dark Theme last time in classic mode, it would revert back to Dark Mode.
or...
If you chose Light Theme in Advanced Mode, when switching to Classic Mode, it would remain in the Light Theme.

Either way, the app reverts to the Arduino Light Theme.

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [1903]

**Comment by svenefftinge** [comment] 2019-11-28 08:21
Duplicate of https://github.com/arduino/arduino-pro-ide/issues/147 (and already fixed in master)

**Closed by svenefftinge** 2019-11-28 08:21 UTC
Labels: bug
