### ISSUE TITLE
Changing between Classic and Pro Mode the color theme is lost

### ISSUE THREAD

**Issue by sstaub** [arduino/arduino-pro-ide#57] opened 2019-10-21 10:54 UTC
**Describe the bug**
When you change form Pro mode with "Dark Theme"  to Classic Mode the theme is lost.
Same in the other direction. It change always to Arduino Light Theme

**Expected behavior**
The color theme should stay if change between modes

**Desktop (please complete the following information):**
 - macOS Catalina
 - Version 0.0.1

**Comment by svenefftinge** [comment] 2019-11-28 08:22
duplicate of https://github.com/arduino/arduino-pro-ide/issues/147 and fixed in master

**Closed by svenefftinge** 2019-11-28 08:22 UTC
Labels: bug
