### ISSUE TITLE
Include library no code

### ISSUE THREAD

**Issue by Ferreira31** [arduino/arduino-pro-ide#175] opened 2020-01-08 22:07 UTC
Nao sei se ja falaram isso, ou se ja tem e nao consegui usar, mas sinto falta de quando clicar em library, ter todas as bibliotecas instaladas no momento, e eu poder simplesmente clicar e ela é adicionada com o #include

**Comment by spoenemann** [comment] 2020-01-13 15:05
Output of Google Translate:

> I don't know if they already said that, or if they already have and I couldn't use it, but I miss when I click on library, have all the libraries installed at the moment, and I can just click and it is added with #include

**Comment by spoenemann** [comment] 2020-01-13 15:15
Duplicate of #76

**Closed by spoenemann** 2020-01-13 15:15 UTC
Labels: enhancement
