### ISSUE TITLE
It is not possible to open libraries examples. At least, I could not find this feature.

### ISSUE THREAD

**Issue by flaviosg** [arduino/arduino-pro-ide#136] opened 2019-11-15 18:43 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by spoenemann** [comment] 2020-01-13 14:35
Duplicate of #70

**Closed by spoenemann** 2020-01-13 14:35 UTC
Labels: enhancement
