### ISSUE TITLE
Feature Request Board Manager

### ISSUE THREAD

**Issue by sstaub** [arduino/arduino-pro-ide#80] opened 2019-10-22 06:45 UTC
When downloading files for a new board, it would helpful to have a progress bar to see the state of downloading, also with estimated download time.
<img width="1072" alt="install" src="https://user-images.githubusercontent.com/6450325/67263378-3f962b80-f4a8-11e9-88d4-2af9b4a41a3a.png">

**Comment by nikilase** [comment] 2019-10-22 09:13
Duplicate of #11

**Closed** 2020-01-13 12:35 UTC
Labels: enhancement
