### ISSUE TITLE
Cannot close tab in classic view

### ISSUE THREAD

**Issue by toogooda** [arduino/arduino-pro-ide#207] opened 2020-02-10 03:59 UTC
**Describe the bug**
There is no way to close a tab in the classic mode the little 'X' is missing. If you change to advanced view you can close it.

**To Reproduce**
1. open any ino file
2.change to classic view
3. try to close the tab

**Expected behavior**
'X' should apear on tab so you can close it, as it does in Pro view.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows10
 - Version 0.4

**Additional context**
Sometimes even if you delete the tab in Pro view then switch back to Classic the tab is back again :(

**Comment by per1234** [comment] 2020-02-10 08:49
Closing as duplicate of https://github.com/arduino/arduino-pro-ide/issues/193

**Closed by per1234** 2020-02-10 08:49 UTC
Labels: bug
