### ISSUE TITLE
Opening projects with large file count causes issues (too many tabs)

### ISSUE THREAD

**Issue by ubidefeo** [arduino/arduino-pro-ide#416] opened 2021-02-05 16:18 UTC
**Describe the bug**
Projects such as Marlin 3D printer firmware contain a large amount of files.
To allow users to compile this in Arduino IDE (Marlin suggests to use the Makefile or PlatformIO for compilation) and not show the 1600+ tabs, most files have been moved into a subfolder named src.
When the IDE requests the file list to the CLI, it obtains a full list because of recursion.
Such recursion should not be permitted and only the content inside the root of the sketch folder should be returned.
On my machine it’s been opening the project for the past 15 minutes... and counting.

**To Reproduce**
1. Download Marlin 2 https://github.com/MarlinFirmware/Marlin
2. Copy the folder `Marlin` to your Sketchbook
3. Launch IDE Pro
4. Open the Marlin Sketch
5. Leave the house and come back next week 😁 
6. The tabs will keep opening

**Expected behavior**
Only 4 tabs should appear (the 4 supported files in the Sketch):
- `Marlin.ino`
- `Configuration.h`
- `Configuration_adv.h`
- `Version.h`

**Screenshots**

IDE Pro
<img width="1318" alt="Screenshot 2021-02-05 at 17 12 45" src="https://user-images.githubusercontent.com/1894487/107058865-6c716d80-67d5-11eb-8efb-ec7bc3870a96.png">
IDE Java
<img width="1267" alt="Screenshot 2021-02-05 at 17 13 22" src="https://user-images.githubusercontent.com/1894487/107059131-b4909000-67d5-11eb-81f5-c9959795e905.png">

**Desktop (please complete the following information):**
 - OS: Windows/Mac/Linux
 - Version: 0.1.3-nightly.20210204

**Additional context**
Opened a related issue for the CLI https://github.com/arduino/arduino-cli/issues/1173

**Comment by ubidefeo** [comment] 2021-02-05 16:26
@kittaakos I have assigned this to you just for tracking reasons, but if the CLI returns the correct list in theory you won't have to do anything

**Comment by kittaakos** [comment] 2021-02-05 17:22
This issue is the duplicate of https://github.com/arduino/arduino-pro-ide/issues/373. It's a CLI issue.

**Comment by kittaakos** [comment] 2021-02-05 17:23
> but if the CLI returns the correct list in theory you won't have to do anything

Yes.

Closing, it's a duplicate.

**Closed** 2021-02-05 17:23 UTC
Labels: bug
